from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field

ArticleStatus = Literal["missing", "stub", "fuzzy", "working", "deep"]
"""The knowledge level of each KDB concept reflects how much the user currently knows about a topic

missing = not in DB
stub = placeholder
fuzzy = partial
working = solid
deep = expert"""


SourceType = Literal["blog", "wikipedia", "github", "arxiv", "youtube"]

ResearchLayer = Literal["intuition", "mechanism", "formalism"]
"""The three levels every concept note is written at."""


# --------------------------------------------------------------------------- #
# ENTITIES                                                                    #
# --------------------------------------------------------------------------- #


class ConceptNode(BaseModel):
    """A single node that represents a learneable user cencept and emitted by the Planner"""

    concept_id: str = Field(description="a slug-case concept identifier e.g. 'nf4-datatype'")
    concept_name: str = Field(
        description="User facing name of the concept represented by the node e.g 'NF4 Quantization'"
    )
    rationale: str = Field(
        description="A short reasoning why this concept must be introduced into the Knowledge DB"
    )
    depth: int = Field(ge=0, le=4, description="Manages the recursive depth of each topic")
    prereqs: list[str] = Field(
        default_factory=list,
        description="concept_ids that must be learned first before the current concept",
    )
    existing_status: ArticleStatus = Field(
        description="current status of this concept in the KB index"
    )


class Source(BaseModel):
    """A single citation that is used to explain a concept"""

    source_title: str = Field(description="the title of the source article")
    source_url: str = Field(description="The URL of the source article")
    source_type: Literal[SourceType] = Field(description="the type of source")


class ComputedExample(BaseModel):
    """A tool-computed and verified example - provides verified rogor for explained concepts"""

    description: str = Field(description="What this example is about")
    inputs: dict[str, Any] = Field(description="Input for the computation to be performed")
    output: str = Field(description="A rendered results, example a matrix etc")
    tool_used: Literal["numpy", "manual_calculation"] = Field(
        description="Tool used for performing the calculation"
    )


class KBContent(BaseModel):
    """A current snapshot of the KB state Planner reads / receives at the start of a user request"""

    existing_concepts: dict[str, dict[str, str]] = Field(
        default_factory=dict, description="concept -> {status, summary}"
    )
    prereq_graph: list[tuple[str, str]] = Field(default_factory=list)
    style_exemplars: list[str] = Field(
        default_factory=list, description="full notes used for few-shot style anchoring"
    )


# --------------------------------------------------------------------------- #
# Node outputs (boundary payloads)                                            #
# --------------------------------------------------------------------------- #


class PlannerOutput(BaseModel):
    concept_dag: list[ConceptNode]
    reasoning: str = Field(description="Short justification for each selected concept node")


class ResearchOutput(BaseModel):
    concept_id: str
    concept_name: str
    research_layer: ResearchLayer = Field(description="Which level of research is this")
    content_markdown: str = Field(
        description="The research content generated by the current research level"
    )
    sources: list[Source]
    computed_examples: list[ComputedExample] = Field(default_factory=list)
    content_confidence: float = Field(
        ge=0.0, le=1.0, description="The confidence threshold of the researcher's output"
    )
    fuzzy_areas: list[str] = Field(
        description="A list of ideas that this researches could not fully solve"
    )


class PrereqEdge(BaseModel):
    from_concept: str = Field(description="concept_id of the dependent concept")
    to_concept: str = Field(description="concept_id of the prerequisite")


class LibrarianOutput(BaseModel):
    concept_id: str
    frontmatter: dict[str, str] = Field(description="YAML serialisable note metadata")
    markdown_body: str = Field(
        description="The entire body of the explained topic given by the user initially"
    )
    new_status: ArticleStatus
    prereq_edges: list[PrereqEdge] = Field(
        default_factory=list,
        description="Prerequisite edges to add to the concept graph",
    )
    reconciliation_flags: list[str] = Field(
        default_factory=list,
        description="contradictions/updates vs existing notes that need user review",
    )
