"""The planner node is responsible for doing most of the heavy lifting
1. It generates a tentative list of proposals with `create_concept_proposals`
2. Enforces caps (rules on proposal validity, depth, costs etc) and generates a plan for research
   with `create_plan_from_proposals`
3. Finalises the proposals for downstream researchers to pick up
"""

from __future__ import annotations

import logging
from typing import cast

from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.messages import HumanMessage, SystemMessage
from pydantic import BaseModel, Field

from agent_myla.domain.models import ArticleStatus, ConceptNode, KBContent, PlannerOutput
from agent_myla.domain.state import TutorState
from agent_myla.llm.factory import get_planner_llm
from agent_myla.prompts.planner_prompts import PLANNER_PROMPT, planner_user_prompt

log = logging.getLogger(__name__)


class ConceptProposal(BaseModel):
    """A candidate proposal generated by the LLM"""

    concept_id: str = Field(description="The name of the concept proposal")
    concept_name: str = Field(description="The user facing name of the concept proposal")
    reason: str = Field(
        description="The brief explanation why the proposal was chosen as a candidate proposal"
    )
    depth: int = Field(description="Determines if this a root concept or a sub-concept")
    prereqs: list[str] = Field(
        description="a list of pre-requisites for this concept", default_factory=list
    )


class FinalPlannedConcepts(BaseModel):
    """A list of concrete proposals generated by the Planner"""

    concepts: list[ConceptProposal] = Field(description="a list of concepts", default_factory=list)


async def _fake_create_concept_proposals(
    topic: str, kb_content: KBContent
) -> list[ConceptProposal]:
    return [
        ConceptProposal(
            concept_id=topic,
            concept_name=topic,
            depth=0,
            prereqs=[f"{topic}-foundation"],
            reason="A root topic",
        ),
        ConceptProposal(
            concept_id=f"{topic}-foundation",
            concept_name=f"{topic}-foundation",
            depth=1,
            prereqs=[],
            reason=f"A dummy sub-topic for {topic}-foundation",
        ),
    ]


async def create_concept_proposals(topic: str, kb_content: KBContent) -> list[ConceptProposal]:
    model: BaseChatModel = get_planner_llm()
    chain = model.with_structured_output(FinalPlannedConcepts)
    existing_ids = [c for c in kb_content.existing_concepts]
    messages = [
        SystemMessage(content=PLANNER_PROMPT),
        HumanMessage(content=planner_user_prompt(topic, existing_ids)),
    ]
    planner_result: FinalPlannedConcepts = cast(FinalPlannedConcepts, await chain.ainvoke(messages))
    log.info(
        f"Planner result contains : {len(planner_result.concepts)}, "
        f"concepts: {[c.concept_name for c in planner_result.concepts]}"
    )
    return [c for c in planner_result.concepts]


async def create_plan_from_proposals(
    concept_proposals: list[ConceptProposal], kb_content: KBContent
) -> PlannerOutput:
    seen_concepts: set[str] = set()
    concept_nodes: list[ConceptNode] = []

    # we will limit the number of concepts to research
    for proposal in sorted(concept_proposals, key=lambda x: x.depth):
        if proposal.concept_id in seen_concepts:
            log.warning("Skipping concept %s reason: already seen", proposal.concept_name)
            continue
        if proposal.depth > 4:  # TODO: Move this to Settings
            log.warning(
                "Skipping concept %s reason: depth %d > 4",
                proposal.concept_name,
                proposal.depth,
            )
            continue
        seen_concepts.add(proposal.concept_id)

        meta = kb_content.existing_concepts.get(proposal.concept_id)
        status_str = meta.get("status", "missing") if meta else "missing"
        current_status = cast(ArticleStatus, status_str)

        concept_nodes.append(
            ConceptNode(
                concept_id=proposal.concept_id,
                concept_name=proposal.concept_name,
                depth=proposal.depth,
                existing_status=current_status,
                prereqs=proposal.prereqs,
                rationale=proposal.reason,
            )
        )

        if len(concept_nodes) >= 10:
            log.warning("Collected 10 concept nodes, skipping all other proposals")
            break

    return PlannerOutput(
        concept_dag=concept_nodes,
        reasoning="Stub reason - enhance!",  # TODO: Add a reasoning for selection
    )


async def _fetch_kb_state(state: TutorState) -> KBContent:
    if "kb_content" not in state:
        log.warning("KB content is not present -> this will create an empty KBContent")
        return KBContent()
    return state["kb_content"]


async def planner_node(state: TutorState) -> dict[str, object]:
    """Decomposes a given topic into smaller concepts, creates a pre-requisites DAG
    after checking the existing KB.
    """
    topic = state["user_topic"]
    log.info("Planner received a new topic=%s", topic)
    kb_content: KBContent = await _fetch_kb_state(state)

    concept_proposals: list[ConceptProposal] = await create_concept_proposals(topic, kb_content)
    verified_plan: PlannerOutput = await create_plan_from_proposals(
        concept_proposals=concept_proposals, kb_content=kb_content
    )

    concepts_to_research: list[ConceptNode] = [
        c for c in verified_plan.concept_dag if c.existing_status != "deep"
    ]
    concepts_skipped: list[ConceptNode] = [
        c for c in verified_plan.concept_dag if c not in concepts_to_research
    ]

    assistant_message: str = (
        f"Planner generated {len(concepts_to_research)}: "
        f"{[c.concept_name for c in concepts_to_research]}. "
        f"Planner skipped {len(concepts_skipped)}: "
        f"{[c.concept_name for c in concepts_skipped]}"
    )
    return {
        "concepts_dag": verified_plan.concept_dag,
        "assistant_message": assistant_message,
        "node_notes": [
            f"[planner] {len(verified_plan.concept_dag)} concepts, "
            f"{len(concepts_to_research)} need research"
        ],
    }
