"""The Researcher is responsible for creating detailed research about the concepts
created by the Planner. Each topic is distributed to three different agenst that
builds intution, mechansim and formalism"""

from __future__ import annotations

import logging
from typing import cast

from langchain_core.language_models import BaseChatModel
from langchain_core.messages import HumanMessage, SystemMessage
from pydantic import BaseModel, Field

from agent_myla.domain.models import ComputedExample, ResearchOutput, Source
from agent_myla.domain.state import ResearchInput
from agent_myla.llm.factory import get_researcher_llm
from agent_myla.prompts.researcher_prompts import (
    get_system_prompt,
    researcher_user_prompt,
)

log = logging.getLogger(__name__)


class _ResearchContent(BaseModel):
    """Internal LLM structured-output schema — excludes context the node already knows."""

    content_markdown: str = Field(description="Full explanation in Markdown")
    sources: list[Source] = Field(description="Citations used; at least one required")
    computed_examples: list[ComputedExample] = Field(
        default_factory=list,
        description="NumPy-verified examples; mechanism layer must supply at least one",
    )
    content_confidence: float = Field(
        ge=0.0, le=1.0, description="Honest self-assessed content confidence (range of 0 to 1)"
    )
    fuzzy_areas: list[str] = Field(
        description=(
            "Plain strings naming sub-topics the researcher could not explain confidently."
            " Each element must be a bare string, not an object. Empty list if none."
        )
    )


async def research_node(
    state: ResearchInput,
    llm: BaseChatModel | None = None,
) -> dict[str, object]:
    """3 Researchers (intuition, mechanism and formalism) distributed via
    the Send API per concept generated by the planner."""
    concept_id: str = state["concept_id"]
    concept_name: str = state["display_name"]
    prereqs: list[str] = state["prereqs_known"]
    layer: str = state["layer"]
    rationale: str = state["rationale"]
    concept_index: int = state["concept_index"]

    log.info("A researcher instance created for concept: %s [%s]", concept_name, layer)

    messages = [
        SystemMessage(content=get_system_prompt(layer=layer)),
        HumanMessage(
            content=researcher_user_prompt(
                concept_name=concept_name, layer=layer, prereqs_known=prereqs, rationale=rationale
            )
        ),
    ]

    model: BaseChatModel = llm if llm is not None else get_researcher_llm()
    # method="function_calling" avoids OpenAI strict-mode schema rejections
    # (dict fields and optional fields are not supported in strict JSON schema mode)
    chain = model.with_structured_output(_ResearchContent, method="function_calling")
    raw_result: _ResearchContent = cast(_ResearchContent, await chain.ainvoke(messages))

    result = ResearchOutput(
        concept_id=concept_id,
        concept_name=concept_name,
        research_layer=layer,
        content_markdown=raw_result.content_markdown,
        sources=raw_result.sources,
        computed_examples=raw_result.computed_examples,
        content_confidence=raw_result.content_confidence,
        fuzzy_areas=raw_result.fuzzy_areas,
    )

    log.info(
        "Researcher [%s/%s] confidence=%.2f sources=%d",
        concept_id,
        layer,
        result.content_confidence,
        len(result.sources),
    )

    return {
        "research_outputs": [result],
        "node_notes": [
            (
                f"[research] concept {concept_index} / layer: {layer} /  {concept_name}"
                f" Produced: {len(result.content_markdown)} words"
            )
        ],
    }
